[package]
name = "source_generator"
version = "0.1.0"
authors = ["Johannes Kutning"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
itertools = "0.8"
linked_hash_set = "0.1.4"
